# Dataset paths
data:
    dreamCh:
        pilot: /pilot
        train: /trainingData
        test : /testData
        metadata:
            dir: /metadata
            exams_metadata:   exams_metadata.tsv
            images_crosswalk: images_crosswalk.tsv

    InBreast:
        train: /data/DreamChallenge_mammo/INBreast/AllDICOMs
        metadata:
            dir: /data/DreamChallenge_mammo/INBreast/meta
            images_crosswalk: images_crosswalk.tsv
    KUMC-guro:
        train: /data/KUMC-guro
        metadata:
            dir: /data/KUMC-guro/metadata
            images_crosswalk: images_crosswalk.undersampling.tsv
    KUMC-anam:
        train: /data/KUMC-anam
        metadata:
            dir: /data/KUMC-anam/metadata
            images_crosswalk: images_crosswalk.undersampling.tsv

# Preprocessing pipeline & applied methods
preprocessing:
    pipeline: [modify, feature, adjsut]

    # cv2.COLORMAP_[GRAY, BONE]

    modify:
        # method  [resize, flip, trim, padding]
        pipeline: [flip, resize]


# Preprocessing result root directory path
resultDir: /preprocessedData
logDir   : /preprocessedData/log/
